### ISSUE TITLE
Add Settings page

### ISSUE THREAD

**Issue by allen505** [allen505/save-for-later-firefox#11]
Add a new settings page with the following features:
- [ ] #10 Toggle for: Open the saved tabs in current window or new window
- [ ]  Toggle for: Auto delete Save on opening the Save
- [ ] Add a tab:  What's new in this release page (with contributors who worked for this release)
- [ ] Add a tab: For Donation/Contributions
- [ ] #7 Add a tab: To create new or manage existing labels which can be added to each Save
- [ ] #3 Toggle for: Local Storage or Sync Storage

**Comment by dnknn** [comment]
@allen505 
Two important functional requirements can greatly enhance the charm of this extension!

- # https://github.com/allen505/save-for-later/issues/12
- # https://github.com/allen505/save-for-later/issues/13

---
Supplementary note: No need to add right-click menu ,  If you want to add it by any chance, please must have the ON/OFF option!
(If all extensions are forced to display the right-click menu items, then the height of the right-click menu list will cover the entire display....^_^)
